### ISSUE TITLE
请问 如何 息屏操控  就像 scrcpy 那样

### ISSUE THREAD

**Issue by snudng** [lim1942/django_scrcpy#1]
请问 如何 息屏操控  就像scrcpy 那样

**Comment by lim1942** [comment]
不知道你问的是不是锁屏键，鼠标点击power键

**Comment by snudng** [comment]
不是 , 是在息屏状态下(应该是假息屏)&nbsp; 进行远程操控，&nbsp; 就像 github 上&nbsp;scrcpy (https://github.com/Genymobile/scrcpy) 这个效果一样，&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lim1942/django_scrcpy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月3日(星期二) 下午2:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lim1942/django_scrcpy] 请问 如何 息屏操控  就像 scrcpy 那样 (Issue #1)





 
不知道你问的是不是锁屏键，鼠标点击power键

**Comment by lim1942** [comment]
那好像不支持，目前投屏就是手机屏幕的镜像，

**Comment by lim1942** [comment]
息屏操控 已经完成。
