### ISSUE TITLE
手机屏幕右侧会多显示一些，如图

### ISSUE THREAD

**Issue by Magicfengge** [lim1942/django_scrcpy#2]
![image](https://user-images.githubusercontent.com/47941521/211704688-bd54409b-a3dc-4398-a09a-5b21e11631ae.png)
麻烦看看，手机右侧出现这种情况

**Comment by lim1942** [comment]
这个不同设备都会有一点，不影响使用的吧

**Comment by lim1942** [comment]
配置页面多配置几种分辨率试试看，部分分辨率下会有这种情况

**Comment by Magicfengge** [comment]
应该是每台手机都会这样，我试了需要调整crop参数

**Comment by lim1942** [comment]
Crop参数是屏幕区域裁切。我这边出现右边多，都是通过调整投屏尺寸参数解决的，发自我的 iPhone在 2023年1月13日，18:04，Magicfengge ***@***.***> 写道：﻿
应该是每台手机都会这样，我试了需要调整crop参数
