### ISSUE TITLE
failed to get the Python codec of the file system encoding

### ISSUE THREAD

**Issue by JunXiaoRuo** [lim1942/django_scrcpy#7]
![image](https://github.com/lim1942/django_scrcpy/assets/47996900/e874dda3-b6d6-4c9d-9dad-672052ff7737)

**Comment by lim1942** [comment]
看着像python环境没装好，试试这个集成包，解压里面就能运行(先看里面文档)，https://github.com/lim1942/django_scrcpy/releases/download/2.6/django_scrcpy2.6_win_x86_64.zip

**Comment by JunXiaoRuo** [comment]
我就是用的这个包，然后双击start.bat就一闪而过，然后我打开这个bat文件在cmd 一条一条执行，就出现了现在这个问题。。我这个系统安装了宝塔，会不会是宝塔自带的python冲突了，该怎么办

**Comment by lim1942** [comment]
看到你图片上报的python3.8，应该是python3.10环境。要不换个干净的win电脑试试看
